### ISSUE TITLE
轮子哥你好，请教个问题

### ISSUE THREAD

**Issue by NAIVEddd** [vczh/tinymoe#3]
` struct CodeError `
`		{ `
`			typedef vector<CodeError>				List; `
`                                                                                 `
`			CodeToken						position; `
`			string_t						message; `
`		}; `
在这段代码里，为什么要把vector定义在类里边，这样不会导致添加元素的时候每次都添加一个空vector,浪费很多空间？

**Comment by clones1201** [comment]
这只是typedef而已啊

**Comment by NAIVEddd** [comment]
多谢多谢。明白了！
