### ISSUE TITLE
这个语言可以改用中文关键字，并去除空格吗？

### ISSUE THREAD

**Issue by hummerstudio** [vczh/tinymoe#4]
在知乎的[这个问题](https://www.zhihu.com/question/26071216)里发现的这个项目，请问这个语言能否改成使用中文关键字，并且去除空格？这样更符合中文语法习惯。

**Comment by nobodxbodon** [comment]
@hummerstudio  作者已经在[这里]发表了设计思路. 不妨自行实现.

**Comment by vczh** [comment]
@nobodxbodon 说得对，@hummerstudio 就当留给你一个作业（逃
